version: '3.7'
services:
  neo4j:
    image: neo4j:3.4
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - type: volume
        source: neo4j-3-data
        target: /var/lib/neo4j/data
    networks:
      - shared-network

volumes:
  neo4j-3-data:

networks:
  shared-network:
    external: true
