version: '3.7'
services:
  redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - type: volume
        source: redis-6-data
        target: /data
    networks:
      - shared-network

volumes:
  redis-6-data:

networks:
  shared-network:
    external: true
