version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - type: volume
        source: jenkins-data
        target: /var/jenkins_home
volumes:
  jenkins-data: