version: '3.7'
services:
  postgres:
    build: docker/postgres
    ports:
      - 5432:5432
    env_file:
      - variables.env
    volumes:
      - type: volume
        source: postgres-12-data
        target: /var/lib/postgresql/data
    networks:
      - shared-network

volumes:
  postgres-12-data:

networks:
  shared-network:
    external: true